# Generated by Django 4.2.4 on 2024-11-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_company_details_company_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_control', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='audit_files/')),
                ('status', models.CharField(choices=[('implemented', 'Implemented'), ('not_implemented', 'Not Implemented'), ('semi_implemented', 'Semi Implemented')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.company')),
            ],
        ),
    ]
