# Generated by Django 4.2.4 on 2024-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_company_contact_number_alter_company_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfile',
            name='status',
            field=models.CharField(blank=True, choices=[('implemented', 'Implemented'), ('not_implemented', 'Not Implemented'), ('semi_implemented', 'Semi Implemented')], max_length=50, null=True),
        ),
    ]
