# Generated by Django 4.1.13 on 2024-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_company_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
